INSERT INTO Empresa (Nome) VALUES ('Banco do Brasil')
INSERT INTO Empresa (Nome) VALUES ('Petrobrás')
INSERT INTO Empresa (Nome) VALUES ('Embraer')
INSERT INTO Empresa (Nome) VALUES ('Caixa Econômica Federal')
INSERT INTO Empresa (Nome) VALUES ('Vale do Rio Doce')
INSERT INTO Empresa (Nome) VALUES ('Itaipú')
INSERT INTO Empresa (Nome) VALUES ('Usina de Angra')
INSERT INTO Empresa (Nome) VALUES ('SERRPRO')
INSERT INTO Empresa (Nome) VALUES ('BR Distribuidora')
INSERT INTO Empresa (Nome) VALUES ('ANVISA')